### ISSUE TITLE
Newpipe to Pipepipe

### ISSUE THREAD

**Issue by noraj** [shreyas-a-s/pipepipe-to-newpipe#1]
Did you have something for the other way around?

https://github.com/InfinityLoop1308/PipePipe/issues/199#issuecomment-2227951780

**Comment by shreyas-a-s** [comment]
To me exporting from newpipe and importing to pipepipe works as expected both for the whole database as well as just the subscriptions. Could you share the json file that is not able import to pipepipe? That way I can check for any issues.

**Comment by noraj** [comment]
I have Newpipe 0.27.0 and Pipepipe 3.5.0. It's not that it's not working, it's that I don't have a proper option to interface both.

In Newpipe:

1. Settings
2. Backup and recovery
3. Export database (as explained in https://github.com/InfinityLoop1308/PipePipe/issues/199#issuecomment-2227951780 it gives me a Zip file containing: newpipe.db, newpipe.settings, preferences.json)

In Pipepipe:

1. (There is no _Backup and recovery_ menu under _Settings_)
2. Subscriptions
3. Import from
    - Previous export (doesn't see the newpipe zip or the newpipe.db)
    - Youtube (subscriptions.csv)
    - Soundcloud

Pipepipe seems to be expecting a json, how could you exports a JSON subscription files from Newpipe?

**Comment by noraj** [comment]
Update: ok it's just that the export/import options on Pipepipe are not under the same place: it's under `Settings > Content > Export database` rather than `Settings > Backup and recovery > Export database`.

So my bad, there is no need.

**Comment by shreyas-a-s** [comment]
No problem, @noraj. I'm glad you've found the solution.

Newpipe sometime recently got a new update and it was in that update the settings got redesigned a bit. That's why the difference in settings locations between the two.
